// This code is generated by command: npm run markdown2code
/**
 * Create a response helper.
 *
 * @params {Number} statusCode
 * @returns {Function} awsLambdaResponse helper
 */

function response (statusCode) {
  /**
   * AWS Lambda response helper.
   *
   * @params {Object|null} body
   * @params {Object} [headers]
   * @returns {Object} responseObj required by AWS Lambda Proxy integration
   */

  function awsLambdaResponse (body, headers) {
    body = body === null ? null : JSON.stringify(body)
    headers = typeof headers === 'object' ? headers : { 'Content-Type': 'application/json' }

    const responseObj = {
      isBase64Encoded: false,
      headers,
      statusCode,
      body
    }

    return responseObj
  }
  return awsLambdaResponse
}

module.exports = response
